name: Continuous Integration wit GitHub Actions

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build Apllication JAR
      working-directory: cursoSpringBoot
      run: mvn clean package
      
    - name: Docker Compose Build
      run: docker compose build

    - name: Push to DockerHub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/curso-spring-boot-rest:latest ${{ secrets.DOCKER_USERNAME }}/curso-spring-boot-rest:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/curso-spring-boot-rest:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/curso-spring-boot-rest:${{ github.run_id }}
